services:
  - type: web
    name: qubit-quest
    env: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: bash start.sh
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.8